/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpg.Frames;

import rpg.Controllers.*;

/**
 *
 * @author Christian
 */
public class PauseMenu extends javax.swing.JFrame {
    javax.swing.JFrame previous;
    
    public void setPrevious(javax.swing.JFrame menu) {
        this.previous = menu;
    }
    private String convertDay(int number) {
        String convert = "Day: " + number;
        return convert;
    }
    private String convertTime(int number) {
        String convert = "Time: " + number;
        return convert;
    }
    private String convertNumber(int number) {
        String convert = "" + number;
        return convert;
    }
    
    /**
     * Creates new form PauseMenu
     */
    public PauseMenu() {
        this.setLocation(350, 200);
        initComponents();
        itemFrame.setVisible(false);
        magicFrame.setVisible(false);
        statusFrame.setVisible(false);
        quitFrame.setVisible(false);
        dayVar.setText(this.convertDay(Game.day));
        timeVar.setText(this.convertTime(Game.time));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameHolder = new javax.swing.JPanel();
        buttonFrame = new javax.swing.JPanel();
        itemButton = new javax.swing.JButton();
        magicButton = new javax.swing.JButton();
        statusButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        dayVar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        timeVar = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();
        statusFrame = new javax.swing.JPanel();
        image = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        level = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        expLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        expToLabel = new javax.swing.JLabel();
        hp = new javax.swing.JLabel();
        mp = new javax.swing.JLabel();
        hpMax = new javax.swing.JLabel();
        mpMax = new javax.swing.JLabel();
        stat = new javax.swing.JPanel();
        str = new javax.swing.JTextField();
        con = new javax.swing.JTextField();
        dex = new javax.swing.JTextField();
        Int = new javax.swing.JTextField();
        wis = new javax.swing.JTextField();
        luc = new javax.swing.JTextField();
        strLabel = new javax.swing.JLabel();
        conLabel = new javax.swing.JLabel();
        dexLabel = new javax.swing.JLabel();
        intLabel = new javax.swing.JLabel();
        wisLabel = new javax.swing.JLabel();
        lucLabel = new javax.swing.JLabel();
        affinity = new javax.swing.JPanel();
        air = new javax.swing.JTextField();
        earth = new javax.swing.JTextField();
        fire = new javax.swing.JTextField();
        water = new javax.swing.JTextField();
        airLabel = new javax.swing.JLabel();
        earthLabel = new javax.swing.JLabel();
        fireLabel = new javax.swing.JLabel();
        waterLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        itemFrame = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        Items = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        displayItem = new javax.swing.JTextArea();
        Weapons = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        displayWeapon = new javax.swing.JTextArea();
        Armor = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        displayArmor = new javax.swing.JTextArea();
        KeyItems = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayKey = new javax.swing.JTextArea();
        magicFrame = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        Black = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        displayBlack = new javax.swing.JTextArea();
        White = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        displayWhite = new javax.swing.JTextArea();
        Red = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        displayRed = new javax.swing.JTextArea();
        Blue = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        displayBlue = new javax.swing.JTextArea();
        quitFrame = new javax.swing.JInternalFrame();
        text = new javax.swing.JLabel();
        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pause Menu");
        setBackground(new java.awt.Color(0, 102, 0));

        frameHolder.setBackground(new java.awt.Color(255, 153, 0));

        buttonFrame.setBackground(new java.awt.Color(102, 0, 0));
        buttonFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        itemButton.setText("Items");
        itemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemButtonActionPerformed(evt);
            }
        });

        magicButton.setText("Magic");
        magicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                magicButtonActionPerformed(evt);
            }
        });

        statusButton.setText("Status");
        statusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setPreferredSize(new java.awt.Dimension(50, 50));

        dayVar.setText("1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dayVar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(dayVar)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setPreferredSize(new java.awt.Dimension(50, 50));

        timeVar.setText("1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(timeVar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(timeVar, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonFrameLayout = new javax.swing.GroupLayout(buttonFrame);
        buttonFrame.setLayout(buttonFrameLayout);
        buttonFrameLayout.setHorizontalGroup(
            buttonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(magicButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonFrameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(buttonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(buttonFrameLayout.createSequentialGroup()
                        .addComponent(returnButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        buttonFrameLayout.setVerticalGroup(
            buttonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(itemButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(magicButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(returnButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        statusFrame.setBackground(new java.awt.Color(102, 51, 0));
        statusFrame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        image.setViewportView(jTextPane1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("HP:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("MP:");

        jLabel3.setText("/");

        jLabel4.setText("/");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Level:");

        levelLabel.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("EXP:");

        expLabel.setText("jLabel8");

        jLabel9.setText("/");

        expToLabel.setText("jLabel10");

        hp.setText("jLabel11");

        mp.setText("jLabel12");

        hpMax.setText("jLabel13");

        mpMax.setText("jLabel14");

        javax.swing.GroupLayout levelLayout = new javax.swing.GroupLayout(level);
        level.setLayout(levelLayout);
        levelLayout.setHorizontalGroup(
            levelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(levelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(levelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(levelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(levelLabel))
                    .addGroup(levelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expToLabel))
                    .addGroup(levelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hpMax))
                    .addGroup(levelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mpMax)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        levelLayout.setVerticalGroup(
            levelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(levelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(levelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(levelLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(levelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(expLabel)
                    .addComponent(jLabel9)
                    .addComponent(expToLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(levelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(hp)
                    .addComponent(hpMax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(levelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(mp)
                    .addComponent(mpMax))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Level", level);

        strLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        strLabel.setText("STR");

        conLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        conLabel.setText("CON");

        dexLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dexLabel.setText("DEX");

        intLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        intLabel.setText("INT");

        wisLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        wisLabel.setText("WIS");

        lucLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lucLabel.setText("LUC");

        javax.swing.GroupLayout statLayout = new javax.swing.GroupLayout(stat);
        stat.setLayout(statLayout);
        statLayout.setHorizontalGroup(
            statLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(statLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(strLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(conLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dexLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(intLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wisLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lucLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(str, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(con, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dex, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Int, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wis, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(luc, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(43, 43, 43))
        );
        statLayout.setVerticalGroup(
            statLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(str, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(strLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(statLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(con, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(statLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dexLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(statLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Int, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(statLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wisLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(statLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lucLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Stats", stat);

        airLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        airLabel.setText("Air");

        earthLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        earthLabel.setText("Earth");

        fireLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fireLabel.setText("Fire");

        waterLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        waterLabel.setText("Water");

        javax.swing.GroupLayout affinityLayout = new javax.swing.GroupLayout(affinity);
        affinity.setLayout(affinityLayout);
        affinityLayout.setHorizontalGroup(
            affinityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(affinityLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(affinityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(waterLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(airLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(earthLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fireLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(affinityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(earth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(fire, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(water)
                    .addComponent(air))
                .addGap(38, 38, 38))
        );
        affinityLayout.setVerticalGroup(
            affinityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(affinityLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(affinityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(air, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(airLabel))
                .addGap(18, 18, 18)
                .addGroup(affinityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(earth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(earthLabel))
                .addGap(18, 18, 18)
                .addGroup(affinityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fireLabel))
                .addGap(18, 18, 18)
                .addGroup(affinityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(water, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waterLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Affinity", affinity);

        name.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout statusFrameLayout = new javax.swing.GroupLayout(statusFrame);
        statusFrame.setLayout(statusFrameLayout);
        statusFrameLayout.setHorizontalGroup(
            statusFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(statusFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusFrameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        statusFrameLayout.setVerticalGroup(
            statusFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusFrameLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                    .addComponent(image))
                .addContainerGap())
        );

        itemFrame.setBackground(new java.awt.Color(102, 51, 0));

        displayItem.setColumns(20);
        displayItem.setRows(5);
        jScrollPane6.setViewportView(displayItem);

        javax.swing.GroupLayout ItemsLayout = new javax.swing.GroupLayout(Items);
        Items.setLayout(ItemsLayout);
        ItemsLayout.setHorizontalGroup(
            ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );
        ItemsLayout.setVerticalGroup(
            ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Items", Items);

        displayWeapon.setColumns(20);
        displayWeapon.setRows(5);
        jScrollPane5.setViewportView(displayWeapon);

        javax.swing.GroupLayout WeaponsLayout = new javax.swing.GroupLayout(Weapons);
        Weapons.setLayout(WeaponsLayout);
        WeaponsLayout.setHorizontalGroup(
            WeaponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );
        WeaponsLayout.setVerticalGroup(
            WeaponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Weapons", Weapons);

        displayArmor.setColumns(20);
        displayArmor.setRows(5);
        jScrollPane4.setViewportView(displayArmor);

        javax.swing.GroupLayout ArmorLayout = new javax.swing.GroupLayout(Armor);
        Armor.setLayout(ArmorLayout);
        ArmorLayout.setHorizontalGroup(
            ArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );
        ArmorLayout.setVerticalGroup(
            ArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Armor", Armor);

        displayKey.setColumns(20);
        displayKey.setRows(5);
        jScrollPane1.setViewportView(displayKey);

        javax.swing.GroupLayout KeyItemsLayout = new javax.swing.GroupLayout(KeyItems);
        KeyItems.setLayout(KeyItemsLayout);
        KeyItemsLayout.setHorizontalGroup(
            KeyItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );
        KeyItemsLayout.setVerticalGroup(
            KeyItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Key Items", KeyItems);

        javax.swing.GroupLayout itemFrameLayout = new javax.swing.GroupLayout(itemFrame);
        itemFrame.setLayout(itemFrameLayout);
        itemFrameLayout.setHorizontalGroup(
            itemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        itemFrameLayout.setVerticalGroup(
            itemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        magicFrame.setBackground(new java.awt.Color(102, 51, 0));

        displayBlack.setColumns(20);
        displayBlack.setRows(5);
        jScrollPane7.setViewportView(displayBlack);

        javax.swing.GroupLayout BlackLayout = new javax.swing.GroupLayout(Black);
        Black.setLayout(BlackLayout);
        BlackLayout.setHorizontalGroup(
            BlackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
        );
        BlackLayout.setVerticalGroup(
            BlackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Black", Black);

        displayWhite.setColumns(20);
        displayWhite.setRows(5);
        jScrollPane8.setViewportView(displayWhite);

        javax.swing.GroupLayout WhiteLayout = new javax.swing.GroupLayout(White);
        White.setLayout(WhiteLayout);
        WhiteLayout.setHorizontalGroup(
            WhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
        );
        WhiteLayout.setVerticalGroup(
            WhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("White", White);

        displayRed.setColumns(20);
        displayRed.setRows(5);
        jScrollPane9.setViewportView(displayRed);

        javax.swing.GroupLayout RedLayout = new javax.swing.GroupLayout(Red);
        Red.setLayout(RedLayout);
        RedLayout.setHorizontalGroup(
            RedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
        );
        RedLayout.setVerticalGroup(
            RedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Red", Red);

        displayBlue.setColumns(20);
        displayBlue.setRows(5);
        jScrollPane10.setViewportView(displayBlue);

        javax.swing.GroupLayout BlueLayout = new javax.swing.GroupLayout(Blue);
        Blue.setLayout(BlueLayout);
        BlueLayout.setHorizontalGroup(
            BlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
        );
        BlueLayout.setVerticalGroup(
            BlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Blue", Blue);

        javax.swing.GroupLayout magicFrameLayout = new javax.swing.GroupLayout(magicFrame);
        magicFrame.setLayout(magicFrameLayout);
        magicFrameLayout.setHorizontalGroup(
            magicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        magicFrameLayout.setVerticalGroup(
            magicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        quitFrame.setVisible(true);

        text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text.setText("Do you wish to quit?");

        yesButton.setText("YES");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        noButton.setText("NO");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout quitFrameLayout = new javax.swing.GroupLayout(quitFrame.getContentPane());
        quitFrame.getContentPane().setLayout(quitFrameLayout);
        quitFrameLayout.setHorizontalGroup(
            quitFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quitFrameLayout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(quitFrameLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(yesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        quitFrameLayout.setVerticalGroup(
            quitFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quitFrameLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(quitFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesButton)
                    .addComponent(noButton))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frameHolderLayout = new javax.swing.GroupLayout(frameHolder);
        frameHolder.setLayout(frameHolderLayout);
        frameHolderLayout.setHorizontalGroup(
            frameHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameHolderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(frameHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameHolderLayout.createSequentialGroup()
                    .addContainerGap(108, Short.MAX_VALUE)
                    .addComponent(itemFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(frameHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameHolderLayout.createSequentialGroup()
                    .addContainerGap(107, Short.MAX_VALUE)
                    .addComponent(magicFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(frameHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frameHolderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(quitFrame)
                    .addContainerGap()))
        );
        frameHolderLayout.setVerticalGroup(
            frameHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameHolderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statusFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(frameHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frameHolderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(itemFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(frameHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frameHolderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(magicFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(frameHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frameHolderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(quitFrame)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(frameHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(frameHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemButtonActionPerformed
        itemFrame.setVisible(true);
        magicFrame.setVisible(false);
        statusFrame.setVisible(false);
        displayItem.setText(Inventory.InventoryFrame(1));
        displayWeapon.setText(Inventory.InventoryFrame(2));
        displayArmor.setText(Inventory.InventoryFrame(3));
        displayKey.setText(Inventory.InventoryFrame(4));
    }//GEN-LAST:event_itemButtonActionPerformed

    private void magicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_magicButtonActionPerformed
        itemFrame.setVisible(false);
        magicFrame.setVisible(true);
        statusFrame.setVisible(false);
        displayBlack.setText(magic.magicFrame(0));
        displayWhite.setText(magic.magicFrame(1));
        displayRed.setText(magic.magicFrame(2));
        displayBlue.setText(magic.magicFrame(3));
    }//GEN-LAST:event_magicButtonActionPerformed

    private void statusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButtonActionPerformed
        statusFrame.setVisible(true);
        itemFrame.setVisible(false);
        magicFrame.setVisible(false);
        name.setText(AkashicTrials.hero.firstName + " " + AkashicTrials.hero.lastName + " (" + AkashicTrials.hero.nickName + ")");
        //image.paint(null);
        levelLabel.setText(convertNumber(AkashicTrials.hero.getLvl()));
        expLabel.setText(convertNumber(AkashicTrials.hero.getEXP()));
        expToLabel.setText(convertNumber(AkashicTrials.hero.getExpTo()));
        hp.setText(convertNumber(AkashicTrials.hero.getHP()));
        hpMax.setText(convertNumber(AkashicTrials.hero.getMaxHP()));
        mp.setText(convertNumber(AkashicTrials.hero.getMP()));
        mpMax.setText(convertNumber(AkashicTrials.hero.getMaxMP()));
        str.setText(convertNumber(AkashicTrials.hero.getSTR()));
        con.setText(convertNumber(AkashicTrials.hero.getCON()));
        dex.setText(convertNumber(AkashicTrials.hero.getDEX()));
        Int.setText(convertNumber(AkashicTrials.hero.getINT()));
        wis.setText(convertNumber(AkashicTrials.hero.getWIS()));
        luc.setText(convertNumber(AkashicTrials.hero.getLUC()));
        air.setText(convertNumber(AkashicTrials.hero.getAir()));
        earth.setText(convertNumber(AkashicTrials.hero.getEarth()));
        fire.setText(convertNumber(AkashicTrials.hero.getFire()));
        water.setText(convertNumber(AkashicTrials.hero.getWater()));
    }//GEN-LAST:event_statusButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        AkashicTrials.save.setPrevious(AkashicTrials.pause);
        AkashicTrials.save.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        statusFrame.setVisible(false);
        itemFrame.setVisible(false);
        magicFrame.setVisible(false);
        quitFrame.setVisible(true);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        AkashicTrials.pause.setVisible(false);
        previous.setVisible(true);
    }//GEN-LAST:event_returnButtonActionPerformed

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_yesButtonActionPerformed

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
        quitFrame.dispose();
    }//GEN-LAST:event_noButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PauseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PauseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PauseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PauseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PauseMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Armor;
    private javax.swing.JPanel Black;
    private javax.swing.JPanel Blue;
    private javax.swing.JTextField Int;
    private javax.swing.JPanel Items;
    private javax.swing.JPanel KeyItems;
    private javax.swing.JPanel Red;
    private javax.swing.JPanel Weapons;
    private javax.swing.JPanel White;
    private javax.swing.JPanel affinity;
    private javax.swing.JTextField air;
    private javax.swing.JLabel airLabel;
    private javax.swing.JPanel buttonFrame;
    private javax.swing.JTextField con;
    private javax.swing.JLabel conLabel;
    private javax.swing.JLabel dayVar;
    private javax.swing.JTextField dex;
    private javax.swing.JLabel dexLabel;
    private javax.swing.JTextArea displayArmor;
    private javax.swing.JTextArea displayBlack;
    private javax.swing.JTextArea displayBlue;
    private javax.swing.JTextArea displayItem;
    private javax.swing.JTextArea displayKey;
    private javax.swing.JTextArea displayRed;
    private javax.swing.JTextArea displayWeapon;
    private javax.swing.JTextArea displayWhite;
    private javax.swing.JTextField earth;
    private javax.swing.JLabel earthLabel;
    private javax.swing.JLabel expLabel;
    private javax.swing.JLabel expToLabel;
    private javax.swing.JTextField fire;
    private javax.swing.JLabel fireLabel;
    private javax.swing.JPanel frameHolder;
    private javax.swing.JLabel hp;
    private javax.swing.JLabel hpMax;
    private javax.swing.JScrollPane image;
    private javax.swing.JLabel intLabel;
    private javax.swing.JButton itemButton;
    private javax.swing.JPanel itemFrame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel level;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JTextField luc;
    private javax.swing.JLabel lucLabel;
    private javax.swing.JButton magicButton;
    private javax.swing.JPanel magicFrame;
    private javax.swing.JLabel mp;
    private javax.swing.JLabel mpMax;
    private javax.swing.JLabel name;
    private javax.swing.JButton noButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JInternalFrame quitFrame;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel stat;
    private javax.swing.JButton statusButton;
    private javax.swing.JPanel statusFrame;
    private javax.swing.JTextField str;
    private javax.swing.JLabel strLabel;
    private javax.swing.JLabel text;
    private javax.swing.JLabel timeVar;
    private javax.swing.JTextField water;
    private javax.swing.JLabel waterLabel;
    private javax.swing.JTextField wis;
    private javax.swing.JLabel wisLabel;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
